site_name: LK Docs
nav:
    - Introduction: index.md
    - Authentication: Auth.md
    - PartnerApi: Partner.md
    - About: about.md
    
theme: readthedocs   
theme_dir: custom_theme
site_favicon: favicon.ico